-- Do not manually edit this file, it was auto-generated by dillonkearns/elm-graphql
-- https://github.com/dillonkearns/elm-graphql


module Api.Object.Call exposing (..)

import Api.InputObject
import Api.Interface
import Api.Object
import Api.Scalar
import Api.ScalarCodecs
import Api.Union
import Graphql.Internal.Builder.Argument as Argument exposing (Argument)
import Graphql.Internal.Builder.Object as Object
import Graphql.Internal.Encode as Encode exposing (Value)
import Graphql.Operation exposing (RootMutation, RootQuery, RootSubscription)
import Graphql.OptionalArgument exposing (OptionalArgument(..))
import Graphql.SelectionSet exposing (SelectionSet)
import Json.Decode as Decode


id : SelectionSet Int Api.Object.Call
id =
    Object.selectionForField "Int" "id" [] Decode.int


callee :
    SelectionSet decodesTo Api.Interface.Expr
    -> SelectionSet decodesTo Api.Object.Call
callee object____ =
    Object.selectionForCompositeField "callee" [] object____ Basics.identity


paren :
    SelectionSet decodesTo Api.Object.Token
    -> SelectionSet decodesTo Api.Object.Call
paren object____ =
    Object.selectionForCompositeField "paren" [] object____ Basics.identity


arguments :
    SelectionSet decodesTo Api.Interface.Expr
    -> SelectionSet (Maybe (List decodesTo)) Api.Object.Call
arguments object____ =
    Object.selectionForCompositeField "arguments" [] object____ (Basics.identity >> Decode.list >> Decode.nullable)
